<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FeesLimitsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('fees_limits')->delete();

        if (checkDemoEnvironment()) {
            \DB::table('fees_limits')->insert([
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '5.00000000',
                    'charge_fixed' => '5.00000000',
                    'min_limit' => '5.00000000',
                    'max_limit' => '100000.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Stripe'),
                    'charge_percentage' => '0.20000000',
                    'charge_fixed' => '1.00000000',
                    'min_limit' => '10.00000000',
                    'max_limit' => '2000.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '2.00000000',
                    'charge_fixed' => '5.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => '500.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('PayUmoney'),
                    'charge_percentage' => '4.00000000',
                    'charge_fixed' => '6.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => '500.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '0.12000000',
                    'charge_fixed' => '1.00000000',
                    'min_limit' => '5.00000000',
                    'max_limit' => '80000.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Coinpayments'),
                    'charge_percentage' => '0.01000000',
                    'charge_fixed' => '1.00000000',
                    'min_limit' => '10.00000000',
                    'max_limit' => '1000.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Payeer'),
                    'charge_percentage' => '0.10000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '10.00000000',
                    'max_limit' => '100.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.03000000',
                    'charge_fixed' => '3.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => '2000.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '5.00000000',
                    'charge_fixed' => '10.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => '10000.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '0.12000000',
                    'charge_fixed' => '2.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Transferred'),
                    'payment_method_id' => null,
                    'charge_percentage' => '2.50000000',
                    'charge_fixed' => '3.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => '5000.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Exchange_From'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.12000000',
                    'charge_fixed' => '1.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Request_Received'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.12000000',
                    'charge_fixed' => '1.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '1.00000000',
                    'charge_fixed' => '1.00000000',
                    'min_limit' => '4.00000000',
                    'max_limit' => '399.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Stripe'),
                    'charge_percentage' => '0.75000000',
                    'charge_fixed' => '3.25000000',
                    'min_limit' => '6.00000000',
                    'max_limit' => '100.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '0.75000000',
                    'charge_fixed' => '2.00000000',
                    'min_limit' => '10.00000000',
                    'max_limit' => '500.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('PayUmoney'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '11.00000000',
                    'charge_fixed' => '90.00000000',
                    'min_limit' => '250.00000000',
                    'max_limit' => '5000.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => '2019-04-08 09:35:02',
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Coinpayments'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Payeer'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '1.60000000',
                    'charge_fixed' => '2.30000000',
                    'min_limit' => '25.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '10.00000000',
                    'charge_fixed' => '25.00000000',
                    'min_limit' => '55.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '2.20000000',
                    'charge_fixed' => '4.00000000',
                    'min_limit' => '16.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '0.11000000',
                    'charge_fixed' => '12.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Exchange_From'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.34000000',
                    'charge_fixed' => '2.00000000',
                    'min_limit' => '7.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Exchange_From'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.80000000',
                    'charge_fixed' => '1.60000000',
                    'min_limit' => '4.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Stripe'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('PayUmoney'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '50.00000000',
                    'charge_fixed' => '300.00000000',
                    'min_limit' => '100.00000000',
                    'max_limit' => '5000.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Coinpayments'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Payeer'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Transferred'),
                    'payment_method_id' => null,
                    'charge_percentage' => '1.50000000',
                    'charge_fixed' => '2.60000000',
                    'min_limit' => '30.00000000',
                    'max_limit' => '900.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Transferred'),
                    'payment_method_id' => null,
                    'charge_percentage' => '1.00000000',
                    'charge_fixed' => '1.00000000',
                    'min_limit' => '14.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Request_Received'),
                    'payment_method_id' => null,
                    'charge_percentage' => '2.00000000',
                    'charge_fixed' => '2.80000000',
                    'min_limit' => '56.00000000',
                    'max_limit' => '859.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Request_Received'),
                    'payment_method_id' => null,
                    'charge_percentage' => '2.50000000',
                    'charge_fixed' => '8.23000000',
                    'min_limit' => '11.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('ETH'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '0.00100000',
                    'max_limit' => '1.00000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => '2022-12-20 03:06:49',
                ],
                [
                    'currency_id' => getCurrencyId('ETH'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Coinpayments'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('ETH'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('ETH'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Crypto'),
                    'charge_percentage' => '2.00000000',
                    'charge_fixed' => '0.00540000',
                    'min_limit' => '0.00020000',
                    'max_limit' => '0.40000000',
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Coinbase'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Flutterwave'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => null,
                    'updated_at' => null,
                ]
            ]);
        } else {
            \DB::table('fees_limits')->insert([
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Stripe'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('PayUmoney'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Coinpayments'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Payeer'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Transferred'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Exchange_From'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Request_Received'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Stripe'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('PayUmoney'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => '2019-04-08 09:35:02',
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Coinpayments'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Payeer'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '1.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Withdrawal'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Exchange_From'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Exchange_From'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Mts'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Stripe'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Paypal'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('PayUmoney'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Bank'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Coinpayments'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Payeer'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'No',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Transferred'),
                    'payment_method_id' => null,
                    'charge_percentage' => '1.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Transferred'),
                    'payment_method_id' => null,
                    'charge_percentage' => '1.00000000',
                    'charge_fixed' => '1.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('EUR'),
                    'transaction_type_id' => getTransactionTypeId('Request_Received'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('GBP'),
                    'transaction_type_id' => getTransactionTypeId('Request_Received'),
                    'payment_method_id' => null,
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Coinbase'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'currency_id' => getCurrencyId('USD'),
                    'transaction_type_id' => getTransactionTypeId('Deposit'),
                    'payment_method_id' => getPaymentMethodId('Flutterwave'),
                    'charge_percentage' => '0.00000000',
                    'charge_fixed' => '0.00000000',
                    'min_limit' => '1.00000000',
                    'max_limit' => null,
                    'processing_time' => '0',
                    'has_transaction' => 'Yes',
                    'created_at' => null,
                    'updated_at' => null,
                ]
            ]);
        }
    }
}
