<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class MerchantPaymentsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('merchant_payments')->delete();
        
        DB::table('merchant_payments')->insert([
            [
                'merchant_id' => getMerchantId('Z3IKX4CNC2ULK'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Mts'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => 'DARK8YMXQK0RY',
                'order_no' => '111',
                'item_name' => 'Makeup & cosmetics Items',
                'uuid' => 'DARK8YMXQK0RY',
                'fee_bearer' => 'Merchant',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.15000000',
                'charge_fixed' => '0.00000000',
                'amount' => '9.85000000',
                'total' => '10.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(58),
                'updated_at' => null,
            ],
            [
                'merchant_id' => getMerchantId('Z3IKX4CNC2ULK'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => 'ch_1Cqy89DpvvQP5tMRZI1Zdm9M',
                'order_no' => '111',
                'item_name' => 'Makeup & cosmetics Items',
                'uuid' => 'ANLUTKTANHQVK',
                'fee_bearer' => 'Merchant',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.15000000',
                'charge_fixed' => '0.00000000',
                'amount' => '9.85000000',
                'total' => '10.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(55),
                'updated_at' => null,
            ],
            [
                'merchant_id' => getMerchantId('J7OJ4STR4ZMXJ'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Mts'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => 'CLE9YJPADUZRZ',
                'order_no' => '123',
                'item_name' => 'Home & kitchen excessories',
                'uuid' => 'CLE9YJPADUZRZ',
                'fee_bearer' => 'Merchant',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.08000000',
                'charge_fixed' => '0.00000000',
                'amount' => '4.92000000',
                'total' => '5.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(85),
                'updated_at' => null,
            ],
            [
                'merchant_id' => getMerchantId('J7OJ4STR4ZMXJ'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Mts'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => 'ZGPCGYUNYHT6N',
                'order_no' => '123',
                'item_name' => 'Home & kitchen excessories',
                'uuid' => 'ZGPCGYUNYHT6N',
                'fee_bearer' => 'Merchant',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.03000000',
                'charge_fixed' => '0.00000000',
                'amount' => '1.97000000',
                'total' => '2.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(80),
                'updated_at' => null,
            ],
            [
                'merchant_id' => getMerchantId('J7OJ4STR4ZMXJ'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Mts'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => 'CJIGRGEWD28HB',
                'order_no' => '123',
                'item_name' => 'Home & kitchen excessories',
                'uuid' => 'CJIGRGEWD28HB',
                'fee_bearer' => 'Merchant',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.03000000',
                'charge_fixed' => '0.00000000',
                'amount' => '1.97000000',
                'total' => '2.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(80),
                'updated_at' => null,
            ],
            [
                'merchant_id' => getMerchantId('J7OJ4STR4ZMXJ'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => 'ch_1Cqz29DpvvQP5tMRpkViQp4B',
                'order_no' => '123',
                'item_name' => 'Home & kitchen excessories',
                'uuid' => '2MJZ7BQLHSQZE',
                'fee_bearer' => 'Merchant',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.03000000',
                'charge_fixed' => '0.00000000',
                'amount' => '1.97000000',
                'total' => '2.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(75),
                'updated_at' => null,
            ],
            [
                'merchant_id' => getMerchantId('J7OJ4STR4ZMXJ'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Paypal'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => 'PAY-4JE18994404557142LNKY4IY',
                'order_no' => '123',
                'item_name' => 'Home & kitchen excessories',
                'uuid' => 'Z7IAF48V1UU7D',
                'fee_bearer' => 'Merchant',
                'amount' => '6.89000000',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.10000000',
                'charge_fixed' => '0.00000000',
                'total' => '7.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(74),
                'updated_at' => null,
            ],
            [
                'merchant_id' => getMerchantId('J7OJ4STR4ZMXJ'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => 'ch_1CqzESDpvvQP5tMRSHdcLm11',
                'order_no' => '123',
                'item_name' => 'Home & kitchen excessories',
                'uuid' => '24ONDSASXEA47',
                'fee_bearer' => 'Merchant',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.10000000',
                'charge_fixed' => '0.00000000',
                'amount' => '6.89000000',
                'total' => '7.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(73),
                'updated_at' => null,
            ],
            [
                'merchant_id' => getMerchantId('J7OJ4STR4ZMXJ'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Mts'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => '9HNQSGQSIWL3Q',
                'order_no' => '123',
                'item_name' => 'Home & kitchen excessories',
                'uuid' => '9HNQSGQSIWL3Q',
                'fee_bearer' => 'Merchant',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.06000000',
                'charge_fixed' => '0.00000000',
                'amount' => '3.94000000',
                'total' => '4.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(70),
                'updated_at' => null,
            ],
            [
                'merchant_id' => getMerchantId('J7OJ4STR4ZMXJ'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Paypal'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => 'PAY-6D934105RS1754743LNKZCGI',
                'order_no' => '123',
                'item_name' => 'Home & kitchen excessories',
                'uuid' => '4VYS1EP6ZU6AE',
                'fee_bearer' => 'Merchant',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.06000000',
                'charge_fixed' => '0.00000000',
                'amount' => '3.94000000',
                'total' => '4.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(65),
                'updated_at' => null,
            ],
            [
                'merchant_id' => getMerchantId('Z3IKX4CNC2ULK'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Mts'),
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'gateway_reference' => '36A208F51C4CA',
                'order_no' => null,
                'item_name' => 'Shirt',
                'uuid' => '36A208F51C4CA',
                'fee_bearer' => 'Merchant',
                'percentage' => '6.50000000',
                'charge_percentage' => '2.98935000',
                'charge_fixed' => '5.00000000',
                'amount' => '38.00065000',
                'total' => '45.99000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now()->subDays(30),
            ],
        ]);
    }
}
