<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->delete();

        DB::table('permissions')->insert([
            [
                'group' => 'User',
                'name' => 'view_user',
                'display_name' => 'View User',
                'description' => 'View User',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'User',
                'name' => 'add_user',
                'display_name' => 'Add User',
                'description' => 'Add User',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'User',
                'name' => 'edit_user',
                'display_name' => 'Edit User',
                'description' => 'Edit User',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'User',
                'name' => 'delete_user',
                'display_name' => 'Delete User',
                'description' => 'Delete User',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Transaction',
                'name' => 'view_transaction',
                'display_name' => 'View Transaction',
                'description' => 'View Transaction',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Transaction',
                'name' => 'add_transaction',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Transaction',
                'name' => 'edit_transaction',
                'display_name' => 'Edit Transaction',
                'description' => 'Edit Transaction',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Transaction',
                'name' => 'delete_transaction',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Deposit',
                'name' => 'view_deposit',
                'display_name' => 'View Deposit',
                'description' => 'View Deposit',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Deposit',
                'name' => 'add_deposit',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Deposit',
                'name' => 'edit_deposit',
                'display_name' => 'Edit Deposit',
                'description' => 'Edit Deposit',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Deposit',
                'name' => 'delete_deposit',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Withdrawal',
                'name' => 'view_withdrawal',
                'display_name' => 'View Withdrawal',
                'description' => 'View Withdrawal',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Withdrawal',
                'name' => 'add_withdrawal',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Withdrawal',
                'name' => 'edit_withdrawal',
                'display_name' => 'Edit Withdrawal',
                'description' => 'Edit Withdrawal',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Withdrawal',
                'name' => 'delete_withdrawal',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Transfer',
                'name' => 'view_transfer',
                'display_name' => 'View Transfer',
                'description' => 'View Transfer',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Transfer',
                'name' => 'add_transfer',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Transfer',
                'name' => 'edit_transfer',
                'display_name' => 'Edit Transfer',
                'description' => 'Edit Transfer',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Transfer',
                'name' => 'delete_transfer',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Exchange',
                'name' => 'view_exchange',
                'display_name' => 'View Exchange',
                'description' => 'View Exchange',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Exchange',
                'name' => 'add_exchange',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Exchange',
                'name' => 'edit_exchange',
                'display_name' => 'Edit Exchange',
                'description' => 'Edit Exchange',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Exchange',
                'name' => 'delete_exchange',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Request Payment',
                'name' => 'view_request_payment',
                'display_name' => 'View Request Payment',
                'description' => 'View Request Payment',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Request Payment',
                'name' => 'add_request_payment',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Request Payment',
                'name' => 'edit_request_payment',
                'display_name' => 'Edit Request Payment',
                'description' => 'Edit Request Payment',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Request Payment',
                'name' => 'delete_request_payment',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Revenue',
                'name' => 'view_revenue',
                'display_name' => 'View Revenue',
                'description' => 'View Revenue',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Revenue',
                'name' => 'add_revenue',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Revenue',
                'name' => 'edit_revenue',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Revenue',
                'name' => 'delete_revenue',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Email Template',
                'name' => 'view_email_template',
                'display_name' => 'View Email Template',
                'description' => 'View Email Template',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Email Template',
                'name' => 'add_email_template',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Email Template',
                'name' => 'edit_email_template',
                'display_name' => 'Edit Email Template',
                'description' => 'Edit Email Template',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Email Template',
                'name' => 'delete_email_template',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Activity Log',
                'name' => 'view_activity_log',
                'display_name' => 'View Activity Log',
                'description' => 'View Activity Log',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Activity Log',
                'name' => 'add_activity_log',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Activity Log',
                'name' => 'edit_activity_log',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Activity Log',
                'name' => 'delete_activity_log',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'General Setting',
                'name' => 'view_general_setting',
                'display_name' => 'View General Setting',
                'description' => 'View General Setting',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'General Setting',
                'name' => 'add_general_setting',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'General Setting',
                'name' => 'edit_general_setting',
                'display_name' => 'Edit General Setting',
                'description' => 'Edit General Setting',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'General Setting',
                'name' => 'delete_general_setting',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Social Links',
                'name' => 'view_social_links',
                'display_name' => 'View Social Links',
                'description' => 'View Social Links',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Social Links',
                'name' => 'add_social_links',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Social Links',
                'name' => 'edit_social_links',
                'display_name' => 'Edit Social Links',
                'description' => 'Edit Social Links',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Social Links',
                'name' => 'delete_social_links',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'API Credentials',
                'name' => 'view_api_credentials',
                'display_name' => 'View API Credentials',
                'description' => 'View API Credentials',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'API Credentials',
                'name' => 'add_api_credentials',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'API Credentials',
                'name' => 'edit_api_credentials',
                'display_name' => 'Edit API Credentials',
                'description' => 'Edit API Credentials',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'API Credentials',
                'name' => 'delete_api_credentials',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Payment Methods',
                'name' => 'view_payment_methods',
                'display_name' => 'View Payment Methods',
                'description' => 'View Payment Methods',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Payment Methods',
                'name' => 'add_payment_methods',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Payment Methods',
                'name' => 'edit_payment_methods',
                'display_name' => 'Edit Payment Methods',
                'description' => 'Edit Payment Methods',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Payment Methods',
                'name' => 'delete_payment_methods',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Email Setting',
                'name' => 'view_email_setting',
                'display_name' => 'View Email Setting',
                'description' => 'View Email Setting',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Email Setting',
                'name' => 'add_email_setting',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Email Setting',
                'name' => 'edit_email_setting',
                'display_name' => 'Edit Email Setting',
                'description' => 'Edit Email Setting',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Email Setting',
                'name' => 'delete_email_setting',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Currency',
                'name' => 'view_currency',
                'display_name' => 'View Currency',
                'description' => 'View Currency',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Currency',
                'name' => 'add_currency',
                'display_name' => 'Add Currency',
                'description' => 'Add Currency',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Currency',
                'name' => 'edit_currency',
                'display_name' => 'Edit Currency',
                'description' => 'Edit Currency',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Currency',
                'name' => 'delete_currency',
                'display_name' => 'Delete Currency',
                'description' => 'Delete Currency',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Country',
                'name' => 'view_country',
                'display_name' => 'View Country',
                'description' => 'View Country',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Country',
                'name' => 'add_country',
                'display_name' => 'Add Country',
                'description' => 'Add Country',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Country',
                'name' => 'edit_country',
                'display_name' => 'Edit Country',
                'description' => 'Edit Country',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Country',
                'name' => 'delete_country',
                'display_name' => 'Delete Country',
                'description' => 'Delete Country',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Language',
                'name' => 'view_language',
                'display_name' => 'View Language',
                'description' => 'View Language',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Language',
                'name' => 'add_language',
                'display_name' => 'Add Language',
                'description' => 'Add Language',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Language',
                'name' => 'edit_language',
                'display_name' => 'Edit Language',
                'description' => 'Edit Language',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Language',
                'name' => 'delete_language',
                'display_name' => 'Delete Language',
                'description' => 'Delete Language',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Role',
                'name' => 'view_role',
                'display_name' => 'View Role',
                'description' => 'View Role',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Role',
                'name' => 'add_role',
                'display_name' => 'Add Role',
                'description' => 'Add Role',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Role',
                'name' => 'edit_role',
                'display_name' => 'Edit Role',
                'description' => 'Edit Role',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Role',
                'name' => 'delete_role',
                'display_name' => 'Delete Role',
                'description' => 'Delete Role',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Database Backup',
                'name' => 'view_database_backup',
                'display_name' => 'View Database Backup',
                'description' => 'View Database Backup',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Database Backup',
                'name' => 'add_database_backup',
                'display_name' => 'Add Database Backup',
                'description' => 'Add Database Backup',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Database Backup',
                'name' => 'edit_database_backup',
                'display_name' => 'Edit Database Backup',
                'description' => 'Edit Database Backup',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Database Backup',
                'name' => 'delete_database_backup',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Meta',
                'name' => 'view_meta',
                'display_name' => 'View Meta',
                'description' => 'View Meta',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Meta',
                'name' => 'add_meta',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Meta',
                'name' => 'edit_meta',
                'display_name' => 'Edit Meta',
                'description' => 'Edit Meta',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Meta',
                'name' => 'delete_meta',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Page',
                'name' => 'view_page',
                'display_name' => 'View Page',
                'description' => 'View Page',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Page',
                'name' => 'add_page',
                'display_name' => 'Add Page',
                'description' => 'Add Page',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Page',
                'name' => 'edit_page',
                'display_name' => 'Edit Page',
                'description' => 'Edit Page',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Page',
                'name' => 'delete_page',
                'display_name' => 'Delete Page',
                'description' => 'Delete Page',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Preference',
                'name' => 'view_preference',
                'display_name' => 'View Preference',
                'description' => 'View Preference',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Preference',
                'name' => 'add_preference',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Preference',
                'name' => 'edit_preference',
                'display_name' => 'Edit Preference',
                'description' => 'Edit Preference',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Preference',
                'name' => 'delete_preference',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant',
                'name' => 'view_merchant',
                'display_name' => 'View Merchant',
                'description' => 'View Merchant',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant',
                'name' => 'add_merchant',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant',
                'name' => 'edit_merchant',
                'display_name' => 'Edit Merchant',
                'description' => 'Edit Merchant',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant',
                'name' => 'delete_merchant',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant Payment',
                'name' => 'view_merchant_payment',
                'display_name' => 'View Merchant Payment',
                'description' => 'View Merchant Payment',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant Payment',
                'name' => 'add_merchant_payment',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant Payment',
                'name' => 'edit_merchant_payment',
                'display_name' => 'Edit Merchant Payment',
                'description' => 'Edit Merchant Payment',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant Payment',
                'name' => 'delete_merchant_payment',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Transaction',
                'name' => 'manage_transaction',
                'display_name' => 'Manage Transaction',
                'description' => 'Manage Transaction',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Deposit',
                'name' => 'manage_deposit',
                'display_name' => 'Manage Deposit',
                'description' => 'Manage Deposit',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Withdrawal',
                'name' => 'manage_withdrawal',
                'display_name' => 'Manage Withdrawal',
                'description' => 'Manage Withdrawal',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Transfer',
                'name' => 'manage_transfer',
                'display_name' => 'Manage Transfer',
                'description' => 'Manage Transfer',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Exchange',
                'name' => 'manage_exchange',
                'display_name' => 'Manage Exchange',
                'description' => 'Manage Exchange',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Request Payment',
                'name' => 'manage_request_payment',
                'display_name' => 'Manage Request Payment',
                'description' => 'Manage Request Payment',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant',
                'name' => 'manage_merchant',
                'display_name' => 'Manage Merchant',
                'description' => 'Manage Merchant',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant Payment',
                'name' => 'manage_merchant_payment',
                'display_name' => 'Manage Merchant Payment',
                'description' => 'Manage Merchant Payment',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'User Group',
                'name' => 'view_group',
                'display_name' => 'View User Group',
                'description' => 'View User Group',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'User Group',
                'name' => 'add_group',
                'display_name' => 'Add User Group',
                'description' => 'Add User Group',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'User Group',
                'name' => 'edit_group',
                'display_name' => 'Edit User Group',
                'description' => 'Edit User Group',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'User Group',
                'name' => 'delete_group',
                'display_name' => 'Delete User Group',
                'description' => 'Delete User Group',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Admins',
                'name' => 'view_admins',
                'display_name' => 'View Admins',
                'description' => 'View Admins',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Admins',
                'name' => 'add_admin',
                'display_name' => 'Add Admin',
                'description' => 'Add Admin',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Admins',
                'name' => 'edit_admin',
                'display_name' => 'Edit Admin',
                'description' => 'Edit Admin',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Admins',
                'name' => 'delete_admin',
                'display_name' => 'Delete Admin',
                'description' => 'Delete Admin',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Disputes',
                'name' => 'view_disputes',
                'display_name' => 'View Disputes',
                'description' => 'View Disputes',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Disputes',
                'name' => 'add_dispute',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Disputes',
                'name' => 'edit_dispute',
                'display_name' => 'Edit Dispute',
                'description' => 'Edit Dispute',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Disputes',
                'name' => 'delete_dispute',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Tickets',
                'name' => 'view_tickets',
                'display_name' => 'View Tickets',
                'description' => 'View Tickets',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Tickets',
                'name' => 'add_ticket',
                'display_name' => 'Add Ticket',
                'description' => 'Add Ticket',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Tickets',
                'name' => 'edit_ticket',
                'display_name' => 'Edit Ticket',
                'description' => 'Edit Ticket',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Tickets',
                'name' => 'delete_ticket',
                'display_name' => 'Delete Ticket',
                'description' => 'Delete Ticket',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Dispute',
                'name' => 'manage_dispute',
                'display_name' => 'Manage Dispute',
                'description' => 'Manage Dispute',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Ticket',
                'name' => 'manage_ticket',
                'display_name' => 'Manage Ticket',
                'description' => 'Manage Ticket',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Settings',
                'name' => 'manage_setting',
                'display_name' => 'Manage Settings',
                'description' => 'Manage Settings',
                'user_type' => 'User',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'AppStore Credentials',
                'name' => 'view_appstore_credentials',
                'display_name' => 'View AppStore Credentials',
                'description' => 'View AppStore Credentials',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'AppStore Credentials',
                'name' => 'add_appstore_credentials',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'AppStore Credentials',
                'name' => 'edit_appstore_credentials',
                'display_name' => 'Edit AppStore Credentials',
                'description' => 'Edit AppStore Credentials',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'AppStore Credentials',
                'name' => 'delete_appstore_credentials',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant Groups',
                'name' => 'view_merchant_group',
                'display_name' => 'View Merchant Group',
                'description' => 'View Merchant Group',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant Groups',
                'name' => 'add_merchant_group',
                'display_name' => 'Add Merchant Group',
                'description' => 'Add Merchant Group',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant Groups',
                'name' => 'edit_merchant_group',
                'display_name' => 'Edit Merchant Group',
                'description' => 'Edit Merchant Group',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Merchant Groups',
                'name' => 'delete_merchant_group',
                'display_name' => 'Delete Merchant Group',
                'description' => 'Delete Merchant Group',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'SMS Setting',
                'name' => 'view_sms_setting',
                'display_name' => 'View SMS Setting',
                'description' => 'View SMS Setting',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'SMS Setting',
                'name' => 'add_sms_setting',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'SMS Setting',
                'name' => 'edit_sms_setting',
                'display_name' => 'Edit SMS Setting',
                'description' => 'Edit SMS Setting',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'SMS Setting',
                'name' => 'delete_sms_setting',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Sms Template',
                'name' => 'view_sms_template',
                'display_name' => 'View Sms Template',
                'description' => 'View Sms Template',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Sms Template',
                'name' => 'add_sms_template',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Sms Template',
                'name' => 'edit_sms_template',
                'display_name' => 'Edit Sms Template',
                'description' => 'Edit Sms Template',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Sms Template',
                'name' => 'delete_sms_template',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Admin Security',
                'name' => 'view_admin_security',
                'display_name' => 'View Admin Security',
                'description' => 'View Admin Security',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Admin Security',
                'name' => 'add_admin_security',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Admin Security',
                'name' => 'edit_admin_security',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Admin Security',
                'name' => 'delete_admin_security',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Notification Type',
                'name' => 'view_notification_type',
                'display_name' => 'View Notification Type',
                'description' => 'View Notification Type',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Notification Type',
                'name' => 'add_notification_type',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Notification Type',
                'name' => 'edit_notification_type',
                'display_name' => 'Edit Notification Type',
                'description' => 'Edit Notification Type',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Notification Type',
                'name' => 'delete_notification_type',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Notification Setting',
                'name' => 'view_notification_setting',
                'display_name' => 'View Notification Setting',
                'description' => 'View Notification Setting',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Notification Setting',
                'name' => 'add_notification_setting',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Notification Setting',
                'name' => 'edit_notification_setting',
                'display_name' => 'Edit Notification Setting',
                'description' => 'Edit Notification Setting',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Notification Setting',
                'name' => 'delete_notification_setting',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Conversion Rate Api',
                'name' => 'view_conversion_rate_api',
                'display_name' => 'View Conversion Rate Api',
                'description' => 'View Conversion Rate Api',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Conversion Rate Api',
                'name' => 'add_conversion_rate_api',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Conversion Rate Api',
                'name' => 'edit_conversion_rate_api',
                'display_name' => 'Edit Conversion Rate Api',
                'description' => 'Edit Conversion Rate Api',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Conversion Rate Api',
                'name' => 'delete_conversion_rate_api',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Addon Manager',
                'name' => 'view_addon_manager',
                'display_name' => 'View Addon Manager',
                'description' => 'View Addon Manager',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Addon Manager',
                'name' => 'add_addon_manager',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Addon Manager',
                'name' => 'edit_addon_manager',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Addon Manager',
                'name' => 'delete_addon_manager',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Crypto Provider',
                'name' => 'view_crypto_provider',
                'display_name' => 'View Crypto Provider',
                'description' => 'View Addon Manager',
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Crypto Provider',
                'name' => 'add_crypto_provider',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Crypto Provider',
                'name' => 'edit_crypto_provider',
                'display_name' => 'Edit Crypto Provider',
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Crypto Provider',
                'name' => 'delete_crypto_provider',
                'display_name' => null,
                'description' => null,
                'user_type' => 'Admin',
                'created_at' => Carbon::now()->subDays(800),
                'updated_at' => Carbon::now()->subDays(800),
            ],
            [
                'group' => 'Cache Clear',
                'name' => 'view_cache_clear',
                'display_name' => 'View Cache Clear',
                'description' => 'View Cache Clear',
                'user_type' => 'Admin',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'group' => 'Cache Clear',
                'name' => 'add_cache_clear',
                'display_name' => 'Add Cache Clear',
                'description' => 'Add Cache Clear',
                'user_type' => 'Admin',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'group' => 'Cache Clear',
                'name' => 'edit_cache_clear',
                'display_name' => 'Edit Cache Clear',
                'description' => 'Edit Cache Clear',
                'user_type' => 'Admin',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'group' => 'Cache Clear',
                'name' => 'delete_cache_clear',
                'display_name' => 'Delete Cache Clear',
                'description' => 'Delete Cache Clear',
                'user_type' => 'Admin',
                'created_at' => null,
                'updated_at' => null,
            ]
        ]);
    }
}
