<?php

namespace Modules\KycVerification\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmailTemplatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('email_templates')->insert([
            array(
                'language_id' => getLanguageId('en'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '{Identity/Address} Verification',
                'body' => 'Hi {user},
<br><br>Your {Identity/Address} verification is <b>{approved/pending/rejected}</b>.
<br><br>If you have any questions, please feel free to reply to this email.
<br><br>Regards,
<br><b>{soft_name}</b>',
                'lang' => 'en',
                'type' => 'email',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('ar'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'ar',
                'type' => 'email',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('fr'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'fr',
                'type' => 'email',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('pt'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'pt',
                'type' => 'email',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('ru'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'ru',
                'type' => 'email',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('es'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'es',
                'type' => 'email',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('tr'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'tr',
                'type' => 'email',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('ch'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'ch',
                'type' => 'email',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('en'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '{Identity/Address} Verification',
                'body' => 'Hi {user}, Your {Identity/Address} verification is <b>{approved/pending/rejected}</b>.Regards, {soft_name}.',
                'lang' => 'en',
                'type' => 'sms',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('ar'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'ar',
                'type' => 'sms',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('fr'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'fr',
                'type' => 'sms',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('pt'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'pt',
                'type' => 'sms',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('ru'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'ru',
                'type' => 'sms',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('es'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'es',
                'type' => 'sms',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('tr'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'tr',
                'type' => 'sms',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
            array(
                'language_id' => getLanguageId('ch'),
                'name' => 'Address or Identity Verification',
                'alias' => 'address-or-identity-verification',
                'subject' => '',
                'body' => '',
                'lang' => 'ch',
                'type' => 'sms',
                'status' => 'Active',
                'group' => 'General',
                'created_at' => '2024-06-04 09:33:24',
                'updated_at' => null,
            ),
        ]);
    }
}
