<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ActivityLogsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('activity_logs')->delete();
        
        \DB::table('activity_logs')->insert([
            [
                'user_id' => getAdmin(),
                'type' => 'Admin',
                'ip_address' => '::1',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(15),
                'updated_at' => null,
            ],
            [
                'user_id' => getAdmin(),
                'type' => 'Admin',
                'ip_address' => 'fe80::8121:87d6:eae8:80d3',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:59.0) Gecko/20100101 Firefox/59.0',
                'created_at' => Carbon::now()->subDays(14),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '::1',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(25),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '::1',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(24),
                'updated_at' => null,
            ],
            [
                'user_id' => getAdmin(),
                'type' => 'Admin',
                'ip_address' => 'fe80::8121:87d6:eae8:80d3',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:59.0) Gecko/20100101 Firefox/59.0',
                'created_at' => Carbon::now()->subDays(13),
                'updated_at' => null,
            ],
            [
                'user_id' => getInactiveUser(),
                'type' => 'User',
                'ip_address' => 'fe80::8121:87d6:eae8:80d3',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:59.0) Gecko/20100101 Firefox/59.0',
                'created_at' => Carbon::now()->subDays(90),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '::1',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(15),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(22),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => 'fe80::c8d2:ea6d:c50a:5409',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(14),
                'updated_at' => null,
            ],
            [
                'user_id' => getSuspendedUser(),
                'type' => 'User',
                'ip_address' => '::1',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => null,
            ],
            [
                'user_id' => getAdmin(),
                'type' => 'Admin',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(12),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(21),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(13),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(12),
                'updated_at' => null,
            ],
            [
                'user_id' => getAdmin(),
                'type' => 'Admin',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(11),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '::1',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(19),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(18),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(11),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(17),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(10),
                'updated_at' => null,
            ],
            [
                'user_id' => getAdmin(),
                'type' => 'Admin',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(9),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(8),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => 'fe80::c8d2:ea6d:c50a:5409',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(16),
                'updated_at' => null,
            ],
            [
                'user_id' => getAdmin(),
                'type' => 'Admin',
                'ip_address' => 'fe80::8121:87d6:eae8:80d3',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:59.0) Gecko/20100101 Firefox/59.0',
                'created_at' => Carbon::now()->subDays(8),
                'updated_at' => null,
            ],
            [
                'user_id' => getInactiveUser(),
                'type' => 'User',
                'ip_address' => '192.168.0.108',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(85),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '::1',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(7),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '192.168.0.106',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(15),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '192.168.0.106',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(6),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '192.168.0.106',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(13),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => 'fe80::c8d2:ea6d:c50a:5409',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(12),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => 'fe80::c8d2:ea6d:c50a:5409',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(11),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => 'fe80::c8d2:ea6d:c50a:5409',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(10),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => 'fe80::c8d2:ea6d:c50a:5409',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(9),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(4),
                'updated_at' => null,
            ],
            [
                'user_id' => getAdmin(),
                'type' => 'Admin',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(7),
                'updated_at' => null,
            ],
            [
                'user_id' => getAdmin(),
                'type' => 'Admin',
                'ip_address' => '192.168.0.116',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(5),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => 'fe80::c8d2:ea6d:c50a:5409',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(7),
                'updated_at' => null,
            ],
            [
                'user_id' => getSuspendedUser(),
                'type' => 'User',
                'ip_address' => 'fe80::c8d2:ea6d:c50a:5409',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(90),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '192.168.0.106',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(6),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => 'fe80::c8d2:ea6d:c50a:5409',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(4),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '192.168.0.106',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '192.168.0.106',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
                'created_at' => Carbon::now()->subDays(4),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('user'),
                'type' => 'User',
                'ip_address' => '::1',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 6.1; rv:61.0) Gecko/20100101 Firefox/61.0',
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => null,
            ],
            [
                'user_id' => getUser('merchant'),
                'type' => 'User',
                'ip_address' => '::1',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'user_id' => getAdmin(),
                'type' => 'Admin',
                'ip_address' => '::1',
                'browser_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
