<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CurrenciesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('currencies')->delete();

        if (checkDemoEnvironment()) {
            \DB::table('currencies')->insert([
                [
                    'type' => 'fiat',
                    'name' => 'US Dollar',
                    'symbol' => '$',
                    'code' => 'USD',
                    'rate' => '1.00000000',
                    'logo' => 'icons8-us-dollar-64.png',
                    'default' => '1',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => null,
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'fiat',
                    'name' => 'Pound Sterling',
                    'symbol' => '£',
                    'code' => 'GBP',
                    'rate' => '0.75000000',
                    'logo' => 'icons8-british-pound-64.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => null,
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'fiat',
                    'name' => 'Euro',
                    'symbol' => '€',
                    'code' => 'EUR',
                    'rate' => '0.85000000',
                    'logo' => 'icons8-euro-64.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => null,
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Litecoin Testnet',
                    'symbol' => 'Ł',
                    'code' => 'LTC',
                    'rate' => '0.00000000',
                    'logo' => 'icons8-litecoin-test-48.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => 'MVL6GCCNXXPyAhPZWXxhacTnVNNsQ888Y6',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto_asset',
                    'name' => 'Litecoin (Test)',
                    'symbol' => 'Ł',
                    'code' => 'LTCTEST',
                    'rate' => '0.00000000',
                    'logo' => '1660982923.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => null,
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto_asset',
                    'name' => 'Bitcoin',
                    'symbol' => '฿',
                    'code' => 'BTC',
                    'rate' => '0.00000000',
                    'logo' => '1661050287.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => null,
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Ethereum',
                    'symbol' => 'Ξ',
                    'code' => 'ETH',
                    'rate' => '0.00000000',
                    'logo' => '1671520294.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '0x6BcA3DdEf6c42Cc8B741F8604b7cf7185f016782',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Dogecoin',
                    'symbol' => 'Ð',
                    'code' => 'DOGE',
                    'rate' => '0.00000000',
                    'logo' => '1671523566.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '9rj5rVx4bcrcpkbrAQtK2Fio5mfV1X4Acv',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Avalanche',
                    'symbol' => 'AVAX',
                    'code' => 'AVAX',
                    'rate' => '0.00000000',
                    'logo' => 'avalanche.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '0x38bc3ca817d22a9d17ffe8aa047da02eafafdbb6',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Binance Coin',
                    'symbol' => 'BNB',
                    'code' => 'BNB',
                    'rate' => '0.00000000',
                    'logo' => 'bnb.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '0x38bc3ca817d22a9d17ffe8aa047da02eafafdbb6',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Cardano',
                    'symbol' => 'ADA',
                    'code' => 'ADA',
                    'rate' => '0.00000000',
                    'logo' => 'cardano.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => 'DdzFFzCqrht3NnGZyaCHsJkfmRTJStUNckzCJTRiKyvuuY4A5aF6TqJFJxuKUmPQGcCc9ecc3dKBRXFbRvHuBPTqaSVuDVZY24BZC79u',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Terra',
                    'symbol' => 'LUNA',
                    'code' => 'LUNA',
                    'rate' => '0.00000000',
                    'logo' => 'luna.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => 'terra1vys0vh99x5pyu8kck2qv6ggtk7ffgvfahhm2nn',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Polkadot',
                    'symbol' => 'DOT',
                    'code' => 'DOT',
                    'rate' => '0.00000000',
                    'logo' => 'dot.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '14Y1p3ixsQPW2ogZFESG4c9BwpC7Np2HFCCA74J25nd1ofro',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Solana',
                    'symbol' => 'SOL',
                    'code' => 'SOL',
                    'rate' => '0.00000000',
                    'logo' => 'solana.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '7RbWEoSjMPgmEnPb9LjR6g8njngMTKB26TnUxTTFaCbn',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Tether USD (Ethereum)',
                    'symbol' => 'USDT',
                    'code' => 'USDT',
                    'rate' => '0.00000000',
                    'logo' => 'tether.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '0x38bc3ca817d22a9d17ffe8aa047da02eafafdbb6',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'USD Coin (Tron)',
                    'symbol' => 'USDC',
                    'code' => 'USDC',
                    'rate' => '0.00000000',
                    'logo' => 'usdc.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => 'TQyrtQ8qYcLD7htJu6bZvbPSWJWvB3dXyR',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Ripple',
                    'symbol' => 'XRP',
                    'code' => 'XRP',
                    'rate' => '0.00000000',
                    'logo' => 'ripple.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => 'rDARUUAS43RsxYr1TACpirUu7jrW23exiW',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Monero',
                    'symbol' => 'XMR',
                    'code' => 'XMR',
                    'rate' => '0.00000000',
                    'logo' => 'monero.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '45nBuWbdFBV3BaUD7BAxbg2v3M3ET2KsPH3FfDc6gWqoWS2ejAuiQtuSRBtGdvgd99YdMz458VUzwYGb2HYiy6RnLX425z5',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'TRON',
                    'symbol' => 'TRX',
                    'code' => 'TRX',
                    'rate' => '0.00000000',
                    'logo' => 'tron.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => 'TQyrtQ8qYcLD7htJu6bZvbPSWJWvB3dXyR',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Dash',
                    'symbol' => 'DASH',
                    'code' => 'DASH',
                    'rate' => '0.00000000',
                    'logo' => 'dash.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => 'XkT5fPQCE6RfdsPQLeXkVgQ8g24VCLV5TP',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'VeChain',
                    'symbol' => 'VET',
                    'code' => 'VET',
                    'rate' => '0.00000000',
                    'logo' => 'vechain.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '0xb4a7725bf84e317e7abc084277fa977d6f4c231d',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Tamadoge',
                    'symbol' => 'TAMA',
                    'code' => 'TAMA',
                    'rate' => '0.00000000',
                    'logo' => 'tamadoge.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '0x38bc3ca817d22a9d17ffe8aa047da02eafafdbb6',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Cosmos',
                    'symbol' => 'ATOM',
                    'code' => 'ATOM',
                    'rate' => '0.00000000',
                    'logo' => 'atom.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => 'cosmos1kk8jee5ycl26frr09qtprhpycwarrxsu0rk34g',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Uniswap',
                    'symbol' => 'UNI',
                    'code' => 'UNI',
                    'rate' => '0.00000000',
                    'logo' => 'uniswap.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '0x38bc3ca817d22a9d17ffe8aa047da02eafafdbb6',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto',
                    'name' => 'Bitcoin',
                    'symbol' => '฿',
                    'code' => 'BTC',
                    'rate' => '0.00000000',
                    'logo' => 'bitcoin_crypto.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => '32vBWRpoqhBijdK3hFBGXAYnePhXP3bRpN',
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto_asset',
                    'name' => 'Dogecoin',
                    'symbol' => 'Ɖ',
                    'code' => 'DOGETEST',
                    'rate' => '0.00000000',
                    'logo' => '1671523566.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => null,
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto_asset',
                    'name' => 'Tron',
                    'symbol' => 'TRX',
                    'code' => 'TRXTEST',
                    'rate' => '0.00000000',
                    'logo' => 'tron.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => null,
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                [
                    'type' => 'crypto_token',
                    'name' => 'Tether Token',
                    'symbol' => 'USDT',
                    'code' => 'USDT',
                    'rate' => '0.00000000',
                    'logo' => 'tether.png',
                    'default' => '0',
                    'exchange_from' => 'local',
                    'allowed_wallet_creation' => 'No',
                    'address' => null,
                    'status' => 'Active',
                    'created_at' => null,
                    'updated_at' => null,
                ],
            ]);
        } else {
            \DB::table('currencies')->insert([
                [
                    'type'                   => 'fiat',
                    'name'                   => 'US Dollar',
                    'symbol'                 => '$',
                    'code'                   => 'USD',
                    'rate'                   => '1',
                    'logo'                   => 'icons8-us-dollar-64.png',
                    'exchange_from'          => 'local',
                    'default'                => '1',
                    'status'                 => 'Active',
                ],
                [
                    'type'                   => 'fiat',
                    'name'                   => 'Pound Sterling',
                    'symbol'                 => '£',
                    'code'                   => 'GBP',
                    'rate'                   => '0.75',
                    'logo'                   => 'icons8-british-pound-64.png',
                    'exchange_from'          => 'local',
                    'default'                => '0',
                    'status'                 => 'Active',
                ],
                [
                    'type'                   => 'fiat',
                    'name'                   => 'Euro',
                    'symbol'                 => '€',
                    'code'                   => 'EUR',
                    'rate'                   => '0.85',
                    'logo'                   => 'icons8-euro-64.png',
                    'exchange_from'          => 'local',
                    'default'                => '0',
                    'status'                 => 'Active',
                ],
                [
                    'type'                   => 'crypto',
                    'name'                   => 'Bitcoin',
                    'symbol'                 => '฿',
                    'code'                   => 'BTC',
                    'rate'                   => '0.00',
                    'logo'                   => 'bitcoin_crypto.png',
                    'exchange_from'          => 'local',
                    'default'                => '0',
                    'status'                 => 'Inactive',
                ],
                [
                    'type'                   => 'crypto',
                    'name'                   => 'Litecoin',
                    'symbol'                 => 'Ł',
                    'code'                   => 'LTC',
                    'rate'                   => '0.00',
                    'logo'                   => '1660982923.png',
                    'exchange_from'          => 'local',
                    'default'                => '0',
                    'status'                 => 'Inactive',
                ],
            ]);
        }
    }
}
