<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepositsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('deposits')->delete();
        
        DB::table('deposits')->insert([
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'TWRELLTGYC94E',
                'charge_percentage' => '0.10000000',
                'charge_fixed' => '0.00000000',
                'amount' => '100.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(90),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('GBP'),
                'payment_method_id' => getPaymentMethodId('Paypal'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'YJOKKSAOTMFSW',
                'charge_percentage' => '0.01000000',
                'charge_fixed' => '1.00000000',
                'amount' => '12.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(80),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('john@gmail.com'),
                'currency_id' => getCurrencyId('EUR'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'TR2DLBQFMXIAN',
                'charge_percentage' => '200.00000000',
                'charge_fixed' => '10.00000000',
                'amount' => '4000.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(88),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('nuzhat@gmail.com'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'SDT05UQLRMRTE',
                'charge_percentage' => '1.00000000',
                'charge_fixed' => '0.00000000',
                'amount' => '1000.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(90),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => '30VAJKOU6SAAD',
                'charge_percentage' => '0.10000000',
                'charge_fixed' => '0.00000000',
                'amount' => '100.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(75),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Paypal'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'Y14Y3XYVXYKSP',
                'charge_percentage' => '0.20000000',
                'charge_fixed' => '0.00000000',
                'amount' => '200.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(70),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'Y0LCZJCZBUWAJ',
                'charge_percentage' => '2500.00000000',
                'charge_fixed' => '5.00000000',
                'amount' => '50000.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(68),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('EUR'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'BA0PKZKDJVSCQ',
                'charge_percentage' => '120.00000000',
                'charge_fixed' => '5.00000000',
                'amount' => '100000.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(62),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('GBP'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'QTSJUAZ4LY8Q1',
                'charge_percentage' => '24.00000000',
                'charge_fixed' => '1.00000000',
                'amount' => '20000.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(58),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('irish@gmail.com'),
                'currency_id' => getCurrencyId('EUR'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'FCHG3FVJ7TSOW',
                'charge_percentage' => '0.60000000',
                'charge_fixed' => '5.00000000',
                'amount' => '500.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(45),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('irish@gmail.com'),
                'currency_id' => getCurrencyId('GBP'),
                'payment_method_id' => getPaymentMethodId('Paypal'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => '8K5R21TZWTP7C',
                'charge_percentage' => '40.00000000',
                'charge_fixed' => '2.00000000',
                'amount' => '2000.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(40),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Paypal'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => '3N0J03B6CGBBR',
                'charge_percentage' => '0.50000000',
                'charge_fixed' => '5.00000000',
                'amount' => '10.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(50),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('irish@gmail.com'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Coinpayments'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'XXC9SP2BSHZSK',
                'charge_percentage' => '26.50000000',
                'charge_fixed' => '5.00000000',
                'amount' => '498.50000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(35),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('EUR'),
                'payment_method_id' => getPaymentMethodId('Paypal'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'TKEPEKIOO3QVH',
                'charge_percentage' => '2.00000000',
                'charge_fixed' => '2.00000000',
                'amount' => '100.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(45),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('GBP'),
                'payment_method_id' => getPaymentMethodId('Mts'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'O0YLSQ6PI0JAU',
                'charge_percentage' => '1.00000000',
                'charge_fixed' => '2.00000000',
                'amount' => '100.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(35),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Bank'),
                'bank_id' => getBankId('213423'),
                'file_id' => getFileId('1554635672.txt'),
                'uuid' => 'BAT7VFJ3HH6JZ',
                'charge_percentage' => '0.12000000',
                'charge_fixed' => '1.00000000',
                'amount' => '102.00000000',
                'status' => 'Pending',
                'created_at' => Carbon::now()->subDays(28),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('GBP'),
                'payment_method_id' => getPaymentMethodId('Bank'),
                'bank_id' => getBankId('5465'),
                'file_id' => getFileId('1554640558.jpg'),
                'uuid' => 'KJEBVD2SFRTBO',
                'charge_percentage' => '77.00000000',
                'charge_fixed' => '90.00000000',
                'amount' => '700.00000000',
                'status' => 'Pending',
                'created_at' => Carbon::now()->subDays(20),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('irish@gmail.com'),
                'currency_id' => getCurrencyId('ETH'),
                'payment_method_id' => getPaymentMethodId('Mts'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => '3694048DBE071',
                'charge_percentage' => '0.00000000',
                'charge_fixed' => '0.00000000',
                'amount' => '0.67850000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(25),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('irish@gmail.com'),
                'currency_id' => getCurrencyId('USD'),
                'payment_method_id' => getPaymentMethodId('Stripe'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'F401CAF20D404',
                'charge_percentage' => '1.50000000',
                'charge_fixed' => '1.00000000',
                'amount' => '750.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(12),
                'updated_at' => null,
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('GBP'),
                'payment_method_id' => getPaymentMethodId('Mts'),
                'bank_id' => null,
                'file_id' => null,
                'uuid' => '0EA0C68BA90C9',
                'charge_percentage' => '1.00000000',
                'charge_fixed' => '1.00000000',
                'amount' => '100.00000000',
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(10),
                'updated_at' => null,
            ]
        ]);
    }
}
