<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MetasTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('metas')->delete();

        \DB::table('metas')->insert([
            [
                'url' => 'help',
                'title' => 'Help',
                'description' => 'Help',
                'keywords' => null,
            ],
            [
                'url' => 'about-us',
                'title' => 'About Us',
                'description' => 'About Us',
                'keywords' => null,
            ],
            [
                'url' => 'contact-us',
                'title' => 'Contact Us',
                'description' => 'Contact Us',
                'keywords' => null,
            ],
            [
                'url' => 'header',
                'title' => 'Header',
                'description' => 'Header',
                'keywords' => null,
            ],
            [
                'url' => 'login',
                'title' => 'Login',
                'description' => 'Login',
                'keywords' => null,
            ],
            [
                'url' => 'register',
                'title' => 'Register',
                'description' => 'Register',
                'keywords' => null,
            ],
            [
                'url' => '/',
                'title' => 'Home',
                'description' => 'Home',
                'keywords' => null,
            ],
            [
                'url' => 'dashboard',
                'title' => 'Dashboard',
                'description' => 'Dashboard',
                'keywords' => null,
            ],
            [
                'url' => 'moneytransfer',
                'title' => 'Money Transfer',
                'description' => 'Money Transfer',
                'keywords' => null,
            ],
            [
                'url' => 'transactions',
                'title' => 'Transactions',
                'description' => 'Transactions',
                'keywords' => null,
            ],
            [
                'url' => 'exchanges',
                'title' => 'Money Exchange',
                'description' => 'Money Exchange',
                'keywords' => null,
            ],
            [
                'url' => 'exchange',
                'title' => 'Money Exchange',
                'description' => 'Money Exchange',
                'keywords' => null,
            ],
            [
                'url' => 'merchants',
                'title' => 'Merchant',
                'description' => 'Merchant',
                'keywords' => null,
            ],
            [
                'url' => 'merchant/add',
                'title' => 'Add Merchant',
                'description' => 'Add Merchant',
                'keywords' => null,
            ],
            [
                'url' => 'request_payments',
                'title' => 'Request Payments',
                'description' => 'Request Payments',
                'keywords' => null,
            ],
            [
                'url' => 'request_payment/add',
                'title' => 'Request Payment',
                'description' => 'Request Payment',
                'keywords' => null,
            ],
            [
                'url' => 'request_payment/edit/{id}',
                'title' => 'Request Payment',
                'description' => 'Request Payment',
                'keywords' => null,
            ],
            [
                'url' => 'request_payment/detail/{id}',
                'title' => 'Request Payment',
                'description' => 'Request Payment',
                'keywords' => null,
            ],
            [
                'url' => 'request_payment/completes',
                'title' => 'Request Payment',
                'description' => 'Request Payment',
                'keywords' => null,
            ],
            [
                'url' => 'exchange/view/{id}',
                'title' => 'Money Exchange',
                'description' => 'Money Exchange',
                'keywords' => null,
            ],
            [
                'url' => 'merchant/edit/{id}',
                'title' => 'Edit Merchant',
                'description' => 'Edit Merchant',
                'keywords' => null,
            ],
            [
                'url' => 'merchant/payments',
                'title' => 'Merchant payments',
                'description' => 'Merchant payments',
                'keywords' => null,
            ],
            [
                'url' => 'deposit',
                'title' => 'Deposit',
                'description' => 'Deposit',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/method/{id}',
                'title' => 'Deposit Amount',
                'description' => 'Deposit Amount',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/stripe_payment',
                'title' => 'Deposit With Stripe',
                'description' => 'Deposit With Stripe',
                'keywords' => null,
            ],
            [
                'url' => 'payout',
                'title' => 'Payout',
                'description' => 'Payout',
                'keywords' => null,
            ],
            [
                'url' => 'withdrawal/method/{id}',
                'title' => 'Payout',
                'description' => 'Payout',
                'keywords' => null,
            ],
            [
                'url' => 'payouts',
                'title' => 'Payouts',
                'description' => 'Payouts',
                'keywords' => null,
            ],
            [
                'url' => 'transactions/{id}',
                'title' => 'Transactions',
                'description' => 'Transactions',
                'keywords' => null,
            ],
            [
                'url' => 'request_payment/accept/{id}',
                'title' => 'Request Payment',
                'description' => 'Request Payment',
                'keywords' => null,
            ],
            [
                'url' => 'request_payment/accept/{id}',
                'title' => 'Request Payment',
                'description' => 'Request Payment',
                'keywords' => null,
            ],
            [
                'url' => 'disputes',
                'title' => 'Disputes',
                'description' => 'Disputes',
                'keywords' => null,
            ],
            [
                'url' => 'merchant/detail/{id}',
                'title' => 'View Merchant',
                'description' => 'View Merchant',
                'keywords' => null,
            ],
            [
                'url' => 'dispute/discussion/{id}',
                'title' => 'Dispute Details',
                'description' => 'Dispute Details',
                'keywords' => null,
            ],
            [
                'url' => 'dispute/add/{id}',
                'title' => 'Dispute Add',
                'description' => 'Dispute Add',
                'keywords' => null,
            ],
            [
                'url' => 'send-money',
                'title' => 'Send Money',
                'description' => 'Send Money',
                'keywords' => null,
            ],
            [
                'url' => 'request-money',
                'title' => 'Request Money',
                'description' => 'Request Money',
                'keywords' => null,
            ],
            [
                'url' => 'news',
                'title' => 'News',
                'description' => 'News',
                'keywords' => null,
            ],
            [
                'url' => 'profile',
                'title' => 'User Profile',
                'description' => 'User Profile',
                'keywords' => null,
            ],
            [
                'url' => 'tickets',
                'title' => 'Tickets',
                'description' => 'Tickets',
                'keywords' => null,
            ],
            [
                'url' => 'ticket/add',
                'title' => 'Add Ticket',
                'description' => 'Add Ticket',
                'keywords' => null,
            ],
            [
                'url' => 'ticket/reply/{id}',
                'title' => 'Ticket Reply',
                'description' => 'Ticket Reply',
                'keywords' => null,
            ],
            [
                'url' => 'exchange_of_base_currency',
                'title' => 'Money Exchange',
                'description' => 'Money Exchange',
                'keywords' => null,
            ],
            [
                'url' => 'exchange/exchange-of-base-currency-confirm',
                'title' => 'Money Exchange',
                'description' => 'Money Exchange',
                'keywords' => null,
            ],
            [
                'url' => 'payout/setting',
                'title' => 'Payout',
                'description' => 'Payout',
                'keywords' => null,
            ],
            [
                'url' => 'payout/store',
                'title' => 'Payout',
                'description' => 'Payout',
                'keywords' => null,
            ],
            [
                'url' => 'send-money-confirm',
                'title' => 'Money Transfer',
                'description' => 'Money Transfer',
                'keywords' => null,
            ],
            [
                'url' => 'exchange_to_base_currency',
                'title' => 'Money Exchange',
                'description' => 'Money Exchange',
                'keywords' => null,
            ],
            [
                'url' => 'exchange/exchange-to-base-currency-confirm',
                'title' => 'Money Exchange',
                'description' => 'Money Exchange',
                'keywords' => null,
            ],
            [
                'url' => 'portfolio',
                'title' => 'Portfolio',
                'description' => 'Portfolio',
                'keywords' => null,
            ],
            [
                'url' => 'request_payment/store',
                'title' => 'Request Payment',
                'description' => 'Request Payment',
                'keywords' => null,
            ],
            [
                'url' => 'forget-password',
                'title' => 'Forgot Password',
                'description' => 'Forgot Password',
                'keywords' => null,
            ],
            [
                'url' => 'password/resets/{token}',
                'title' => 'Reset Password',
                'description' => 'Reset Password',
                'keywords' => null,
            ],
            [
                'url' => 'request-money-confirm',
                'title' => 'Request Money',
                'description' => 'Request Money',
                'keywords' => null,
            ],
            [
                'url' => 'request_payment/accepted',
                'title' => 'Request Payment',
                'description' => 'Request Payment',
                'keywords' => null,
            ],
            [
                'url' => 'request_payment/accept-money-confirm',
                'title' => 'Request Payment',
                'description' => 'Request Payment',
                'keywords' => null,
            ],
            [
                'url' => 'policies',
                'title' => 'Policies',
                'description' => 'Policies',
                'keywords' => null,
            ],
            [
                'url' => 'transfer',
                'title' => 'Money Transfer',
                'description' => 'Money Transfer',
                'keywords' => null,
            ],
            [
                'url' => 'withdrawal/confirm-transaction',
                'title' => 'Payout',
                'description' => 'Payout',
                'keywords' => null,
            ],
            [
                'url' => 'request',
                'title' => 'Request Payment',
                'description' => 'Request Payment',
                'keywords' => null,
            ],
            [
                'url' => 'developer',
                'title' => 'Developer',
                'description' => 'Developer Page',
                'keywords' => null,
            ],
            [
                'url' => 'about-us',
                'title' => 'About us',
                'description' => 'About us',
                'keywords' => null,
            ],
            [
                'url' => 'portfoilo',
                'title' => 'Portfoilo',
                'description' => 'Portfoilo',
                'keywords' => null,
            ],
            [
                'url' => 'contact-us',
                'title' => 'Contact Us',
                'description' => 'Contact Us',
                'keywords' => null,
            ],
            [
                'url' => 'phone-verification',
                'title' => 'Verfy Phone',
                'description' => 'Verfy Phone',
                'keywords' => null,
            ],
            [
                'url' => 'authenticate',
                'title' => '2-Factor Authentication',
                'description' => '2-Factor Authentication',
                'keywords' => null,
            ],
            [
                'url' => 'profile/2fa',
                'title' => '2-FA',
                'description' => '2-FA',
                'keywords' => null,
            ],
            [
                'url' => '2fa',
                'title' => '2-Factor Authentication',
                'description' => '2-Factor Authentication',
                'keywords' => null,
            ],
            [
                'url' => 'google2fa',
                'title' => 'Google 2FA',
                'description' => 'Google 2FA',
                'keywords' => null,
            ],
            [
                'url' => 'exchange-of-money',
                'title' => 'Money Exchange',
                'description' => 'Money Exchange',
                'keywords' => null,
            ],
            [
                'url' => 'exchange-of-money-success',
                'title' => 'Money Exchange',
                'description' => 'Money Exchange',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/bank-payment',
                'title' => 'Deposit',
                'description' => 'Deposit',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/payeer/payment/success',
                'title' => 'Deposit With Payeer',
                'description' => 'Deposit With Payeer',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/checkout/payment/success',
                'title' => 'Deposit with 2checkout',
                'description' => 'Deposit with 2checkout',
                'keywords' => null,
            ],
            [
                'url' => 'merchant/payment',
                'title' => 'Merchant Payment',
                'description' => 'Merchant Payment',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/stripe-payment/success',
                'title' => 'Deposit With Stripe',
                'description' => 'Deposit With Stripe',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/paypal-payment/success',
                'title' => 'Deposit With PayPal',
                'description' => 'Deposit With PayPal',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/bank-payment/success',
                'title' => 'Deposit With Bank',
                'description' => 'Deposit With Bank',
                'keywords' => null,
            ],
            [
                'url' => 'check-user-status',
                'title' => 'Suspended',
                'description' => 'Suspended',
                'keywords' => null,
            ],
            [
                'url' => 'check-request-creator-suspended-status',
                'title' => 'Suspended',
                'description' => 'Suspended',
                'keywords' => null,
            ],
            [
                'url' => 'check-request-creator-inactive-status',
                'title' => 'Inactive',
                'description' => 'Inactive',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/store',
                'title' => 'Deposit Fund',
                'description' => 'Deposit',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/coinpayment-transaction-info',
                'title' => 'Coinpayment Summery',
                'description' => 'Coinpayment Summery',
                'keywords' => null,
            ],
            [
                'url' => 'wallet-list',
                'title' => 'Wallet List',
                'description' => 'Wallet List',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/paypal-payment/success/{amount}',
                'title' => 'Deposit With PayPal',
                'description' => 'Deposit With PayPal',
                'keywords' => null,
            ],
            [
                'url' => 'privacy-policy',
                'title' => 'Privacy Policy',
                'description' => 'Privacy Policy',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/confirm',
                'title' => 'Deposit confirm',
                'description' => 'Deposit confirm',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/confirm',
                'title' => 'Deposit confirm',
                'description' => 'Deposit confirm',
                'keywords' => null,
            ],
            [
                'url' => 'deposit/success',
                'title' => 'Deposit Success',
                'description' => 'Deposit Success',
                'keywords' => null,
            ],
            [
                'url' => 'reset-password/{token}',
                'title' => 'Reset Password',
                'description' => 'Reset Password',
                'keywords' => '',
            ],
            [
                'url' => 'register/store-personal-info',
                'title' => 'User Registration',
                'description' => 'User Registration',
                'keywords' => '',
            ],
        ]);
    }
}
