<?php

namespace Modules\TatumIo\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TransactionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('transactions')->insert([
            [
                'user_id' => getUserByEmail('irish@gmail.com'),
                'end_user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('LTCTEST'),
                'payment_method_id' => getPaymentMethodId('TatumIo'),
                'merchant_id' => null,
                'bank_id' => null,
                'file_id' => null,
                'uuid' => '37ED90852E4D5',
                'refund_reference' => null,
                'transaction_reference_id' => 0,
                'transaction_type_id' => getTransactionTypeId('Crypto_Sent'),
                'user_type' => 'registered',
                'email' => null,
                'phone' => null,
                'subtotal' => '0.00200000',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.00000000',
                'charge_fixed' => '0.00000000',
                'total' => '-0.00200000',
                'note' => null,
                'payment_status' => null,
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'end_user_id' => getUserByEmail('irish@gmail.com'),
                'currency_id' => getCurrencyId('LTCTEST'),
                'payment_method_id' => getPaymentMethodId('TatumIo'),
                'merchant_id' => null,
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'A95EC0159E9BF',
                'refund_reference' => null,
                'transaction_reference_id' => 0,
                'transaction_type_id' => getTransactionTypeId('Crypto_Received'),
                'user_type' => 'registered',
                'email' => null,
                'phone' => null,
                'subtotal' => '0.00200000',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.00000000',
                'charge_fixed' => '0.00000000',
                'total' => '0.00200000',
                'note' => null,
                'payment_status' => null,
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(90),
                'updated_at' => Carbon::now()->subDays(90),
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'end_user_id' => null,
                'currency_id' => getCurrencyId('DOGETEST'),
                'payment_method_id' => getPaymentMethodId('TatumIo'),
                'merchant_id' => null,
                'bank_id' => null,
                'file_id' => null,
                'uuid' => '0EF56684414D7',
                'refund_reference' => null,
                'transaction_reference_id' => 0,
                'transaction_type_id' => getTransactionTypeId('Crypto_Received'),
                'user_type' => 'registered',
                'email' => null,
                'phone' => null,
                'subtotal' => '4.00000000',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.00000000',
                'charge_fixed' => '0.00000000',
                'total' => '4.00000000',
                'note' => null,
                'payment_status' => null,
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(85),
                'updated_at' => Carbon::now()->subDays(85),
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'end_user_id' => getUserByEmail('irish@gmail.com'),
                'currency_id' => getCurrencyId('DOGETEST'),
                'payment_method_id' => getPaymentMethodId('TatumIo'),
                'merchant_id' => null,
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'C346154FE1948',
                'refund_reference' => null,
                'transaction_reference_id' => 0,
                'transaction_type_id' => getTransactionTypeId('Crypto_Sent'),
                'user_type' => 'registered',
                'email' => null,
                'phone' => null,
                'subtotal' => '2.00000000',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.00000000',
                'charge_fixed' => '0.00000000',
                'total' => '-2.00000000',
                'note' => null,
                'payment_status' => null,
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(80),
                'updated_at' => Carbon::now()->subDays(80),
            ],
            [
                'user_id' => getUserByEmail('irish@gmail.com'),
                'end_user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('DOGETEST'),
                'payment_method_id' => getPaymentMethodId('TatumIo'),
                'merchant_id' => null,
                'bank_id' => null,
                'file_id' => null,
                'uuid' => 'C346154FE1948',
                'refund_reference' => null,
                'transaction_reference_id' => 0,
                'transaction_type_id' => getTransactionTypeId('Crypto_Received'),
                'user_type' => 'registered',
                'email' => null,
                'phone' => null,
                'subtotal' => '2.00000000',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.00000000',
                'charge_fixed' => '0.00000000',
                'total' => '2.00000000',
                'note' => null,
                'payment_status' => null,
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(75),
                'updated_at' => Carbon::now()->subDays(75),
            ],
            [
                'user_id' => getUserByEmail('irish@gmail.com'),
                'end_user_id' => getUserByEmail('kyla@gmail.com'),
                'currency_id' => getCurrencyId('USDT'),
                'payment_method_id' => getPaymentMethodId('TatumIo'),
                'merchant_id' => null,
                'bank_id' => null,
                'file_id' => null,
                'uuid' => '295F40B9EA335',
                'refund_reference' => null,
                'transaction_reference_id' => 0,
                'transaction_type_id' => getTransactionTypeId('Token_Sent'),
                'user_type' => 'registered',
                'email' => null,
                'phone' => null,
                'subtotal' => '7.00000000',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.00000000',
                'charge_fixed' => '0.00000000',
                'total' => '-7.00000000',
                'note' => null,
                'payment_status' => null,
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(70),
                'updated_at' => Carbon::now()->subDays(70),
            ],
            [
                'user_id' => getUserByEmail('kyla@gmail.com'),
                'end_user_id' => getUserByEmail('irish@gmail.com'),
                'currency_id' => getCurrencyId('USDT'),
                'payment_method_id' => getPaymentMethodId('TatumIo'),
                'merchant_id' => null,
                'bank_id' => null,
                'file_id' => null,
                'uuid' => '295F40B9EA335',
                'refund_reference' => null,
                'transaction_reference_id' => 0,
                'transaction_type_id' => getTransactionTypeId('Token_Received'),
                'user_type' => 'registered',
                'email' => null,
                'phone' => null,
                'subtotal' => '7.00000000',
                'percentage' => '0.00000000',
                'charge_percentage' => '0.00000000',
                'charge_fixed' => '0.00000000',
                'total' => '7.00000000',
                'note' => null,
                'payment_status' => null,
                'status' => 'Success',
                'created_at' => Carbon::now()->subDays(60),
                'updated_at' => Carbon::now()->subDays(60),
            ]
        ]);
    }
}
